[package]
name = "advent-of-code"
version = "0.1.0"
authors = ["Marcelo Lima <marcelowind@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
lazy_static = "1"
pest = "2"
pest_derive = "2"
regex = "1"
